Repository tsrorg/tsr, pull requests merged in 2024-12, with the labels that each got.

#73 perf: use parseFile util to construct dependency graph
  lib/remove.ts
  lib/util/FileService.ts
  lib/util/MemoryFileService.ts
  lib/util/applyCodeFix.test.ts
  lib/util/createDependencyGraph.test.ts
  lib/util/createDependencyGraph.ts
  lib/util/createProgram.ts
  lib/util/edit.ts
  lib/util/findFileUsage.test.ts
  lib/util/findFileUsage.ts
  lib/util/parseFile.ts
  test/helpers/setup.ts
Labels: feature

#75 refactor: add `includeDts` option to `remove()` for clarity
  lib/cli.ts
  lib/remove.ts
  lib/util/regex.ts
  test/fixtures/include_dts/main.ts
  test/fixtures/include_dts/types.d.ts
  test/include_dts.test.ts
Labels: chore

#78 chore: restore old url
  package.json
Labels: chore

#79 chore: fix syntax workflow in publish
  .github/workflows/publish.yml
Labels: chore

#81 feat: update logic to output results to cli
  lib/tsr.ts
  lib/util/CliEditTracker.ts
  lib/util/CliOutput.ts
  lib/util/EditTracker.ts
  lib/util/Output.ts
  lib/util/edit.ts
Labels: feature

#84 chore: remove helper
  test/helpers/assertEqualOutput.ts
  test/reexport_delete.test.ts
  test/simple.test.ts
  test/skip.test.ts
Labels: chore

#85 docs: update docs for v1
  README.md
  doc/MIGRATING_TO_V1.md
Labels: docs

#86 feat: rename skip to entrypoints
  lib/tsr.ts
  test/include_dts.test.ts
  test/load_tsconfig.test.ts
  test/reexport_delete.test.ts
  test/simple.test.ts
  test/skip.test.ts
Labels: feature

#87 chore: add benchmark for vue core
  benchmark/.gitignore
  benchmark/vue_core.sh
Labels: chore

#88 feat: remove writing to disk log
  lib/tsr.ts
Labels: feature

#90 docs: comparison with knip
  README.md
  media/comparison.png
Labels: docs

#91 docs: add link to migration guide
  README.md
  doc/migration.md
Labels: docs

#92 docs: update migration guide
  doc/migration.md
Labels: docs

#94 chore: dont use bundle option in esbuild
  build.js
  package.json
Labels: chore

#96 feat: replace cac with mri
  README.md
  lib/cli.ts
  lib/util/arg.test.ts
  lib/util/arg.ts
  package-lock.json
  package.json
Labels: feature

#97 docs: update size
  README.md
Labels: docs

#98 feat: detect namespace import usage accurately
  lib/util/edit.test.ts
  lib/util/namespaceUsage.test.ts
  lib/util/namespaceUsage.ts
  lib/util/parseFile.test.ts
  lib/util/parseFile.ts
  package-lock.json
Labels: feature

#100 fix: remove use of task manager
  lib/util/TaskManager.test.ts
  lib/util/TaskManager.ts
  lib/util/edit.ts
Labels: bug

#103 feat: dont call process.exit in tsr()
  README.md
  lib/cli.ts
  lib/main.ts
  lib/tsr.ts
  lib/util/error.ts
  test/include_dts.test.ts
  test/load_tsconfig.test.ts
  test/reexport_delete.test.ts
  test/simple.test.ts
  test/skip.test.ts
Labels: feature

#105 fix: use correct default value for configFile option
  lib/cli.ts
Labels: bug

#106 docs: fix typo
  README.md
Labels: docs

#107 test: add test case for parsing args correctly
  test/fixtures/parse_args/src/a.ts
  test/fixtures/parse_args/src/main.ts
  test/fixtures/parse_args/tsconfig.json
  test/fixtures/parse_args/tsconfig.main.json
  test/parse_args.test.ts
Labels: chore
