Repository tsrorg/tsr, pull requests merged in 2024-09, with the labels that each got.

#12 bugfix: remove export keyword for locally used declaration
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
Labels: bug

#13 bugfix: correctly auto fix when there are multiple export specifiers
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
Labels: bug

#18 feat: handle reexports
  lib/util/CliEditTracker.ts
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
  test/execute.test.ts
  tsconfig.lib.json
  tsconfig.test.json
Labels: feature

#19 feat: remove empty lines
  lib/util/applyCodeFix.test.ts
  lib/util/applyTextChanges.test.ts
  lib/util/applyTextChanges.ts
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
Labels: feature

#21 docs: add explanation about skip option
  README.md
Labels: docs

#30 docs: update readme
  README.md
  media/screenshot.png
Labels: docs

#31 chore: run action fro pull requests
  .github/workflows/ci.yml
Labels: chore

#26 feat: Use relative paths, clean up asserted output
  lib/cli.ts
  lib/remove.ts
  lib/util/CliEditTracker.ts
  package-lock.json
  package.json
  test/execute.test.ts
Labels: feature

#32 docs: add diff example
  README.md
Labels: docs

#33 docs: update screenshot
  media/screenshot.png
Labels: docs

#34 fix: add support for dynamic imports
  lib/util/Graph.test.ts
  lib/util/Graph.ts
  lib/util/collectDynamicImports.test.ts
  lib/util/collectDynamicImports.ts
  lib/util/getFileFromModuleSpecifierText.ts
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
  test/helpers/setup.ts
  tsconfig.lib.json
  tsconfig.test.json
Labels: bug

#35 fix: don't strip async keyword from function declaration
  lib/util/applyTextChanges.test.ts
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
Labels: bug

#36 Fix: `import * as foo from './foo'` is not detected as usage when used with reexport
  lib/util/removeUnusedExport.test.ts
  lib/util/removeUnusedExport.ts
Labels: bug

#37 chore: use js api for node test runner
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
  test.js
Labels: chore

#39 docs: update README
  README.md
Labels: docs

#40 chore: exit with 1 when test fails
  test.js
Labels: chore
